CREATE TABLE APPLICANT (
						ID_APPLICANT INTEGER,
						LAST_NAME VARCHAR(100),
						FIRST_NAME VARCHAR(100),
						COUNTRY VARCHAR(30),
						CITY VARCHAR(30),
						ADRESSE VARCHAR(50),
						MOBILE VARCHAR(20),
						PHONE VARCHAR(20),
						EMAIL VARCHAR(50),
						BIRTHDAY DATE
						);
							
CREATE TABLE PRO_SITUATION (
							ID_PRO_SITUATION INTEGER,
							SITUATION VARCHAR(30),
							SECTOR	VARCHAR(30),
							PROFESSION VARCHAR(30),
							HIRE_DATE DATE,
							CONTRACT_TYPE VARCHAR(20),
							ID_APPLICANT INTEGER
							);
							
CREATE TABLE PROJECT (
					ID_PROJECT INTEGER,
					PROJECT_TYPE VARCHAR(50),
					AMOUNT DECIMAL(10,5),
					MORTGAGE DECIMAL(10,5),
					DURATION DECIMAL(5),
					ID_APPLICANT INTEGER
					);
					
CREATE TABLE INCOME_APPLICANT (
								ID_INCOME_APPLICANT INTEGER,
								SALARY DECIMAL(10,5),
								OTHER_SOURCES DECIMAL(10,5),
								ID_APPLICANT INTEGER
								);
								
CREATE TABLE CHARGES_APPLICANT(
								ID_CHARGES_APPLICANT INTEGER,
								REAL_ESTATE_LOAN VARCHAR(1),
								ACTIVE_LOAN INTEGER,
								LOAN_TYPE VARCHAR(20),
								MONTHLY_AMOUNT DECIMAL(10,5),
								ID_APPLICANT INTEGER
								);
							
CREATE TABLE USERS (
					LOGIN VARCHAR(20),
					EMAIL VARCHAR(50),
					STATUS VARCHAR(1)
					);
					
CREATE TABLE GROUPS (
					ID_GROUP VARCHAR(20),
					LB_GROUP VARCHAR(100)
					);
					
CREATE TABLE USERS_GROUPS (
							ID_GROUP VARCHAR(20),
							LOGIN VARCHAR(20)
							);
							

					
					
					
					
					
					
					
					
					
					
	
	
	
	
	
	
	
	
	
	
	
	